default:
  migrationsRun: false
  logging: false
  synchronize: false
  type: postgres
  host: nest-boiler-postgres
  port: 5432
  username: postgres
  password: password
  database: common
  autoLoadEntities: true
  migrations: ['migration/*{.js}']
  entities: ['infrastructure/**/*.entity{.js}']
# tenant:
