default:
  migrationsRun: false
  logging: false
  synchronize: false
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: common
  autoLoadEntities: true
  migrations: ['migration/*.ts']
  entities: ['dist/src/infrastructure/**/*.entity.js']
## tenant:

