apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: skaffold
.YamlAnchors:
  artifactDefinitions:
    - &api
      name: api
      chartPath: ../charts/api
      valuesFiles:
        - ./commonValues.yaml
        - ./api/values.yaml
profiles:
  - name: api
    deploy:
      helm:
        releases:
          - *api
