apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: skaffold
.YamlAnchors:
  artifactDefinitions:
    - &api
      name: api
      chartPath: ../charts/api
      valuesFiles:
        - ./commonValues.yaml
        - ./api/values.yaml
      artifactOverrides:
        image: keke0123/nest-boiler-dev
      imageStrategy:
        helm: {}
    - &neo4j
      name: neo4j
      remoteChart: neo4j/neo4j-standalone
      valuesFiles:
        - ./neo4j-standalone/values.yaml
      version: 4.4.11
      upgradeOnChange: true
    - &storage
      name: storage
      chartPath: ../charts/storage
      valuesFiles:
        - ./commonValues.yaml
profiles:
  - name: api
    build:
      tagPolicy:
        #   envTemplate:
        #     template: latest
        gitCommit:
          ignoreChanges: false
      artifacts:
        - image: keke0123/nest-boiler-dev
          context: "../../../api"
          docker:
            dockerfile: "Dockerfile.skaffold"
          #   cacheFrom:
          #     - keke0123/nest-boiler-dev
          #     # - keke0123/nest-boiler-dev:latest
          #   buildArgs:
          #     TARGET_ENV: local
          sync:
            # auto: true
            manual:
              - src: "src/**/*.ts"
                dest: src
                strip: "src/"
    deploy:
      helm:
        releases:
          - *api
  - name: neo4j
    deploy:
      helm:
        releases:
          - *neo4j
  - name: storage
    deploy:
      helm:
        releases:
          - *storage
