apiVersion: v1
kind: ConfigMap
metadata:
  name: firebase-config
  labels:
data:
  firebase.json: |
    {
      "projects": {
        "default": "nanafa-test-project"
      },
      "emulators": {
        "ui": {
          "host": "0.0.0.0",
          "enabled": true,
          "port": 4000
        },
        "singleProjectMode": true,
        "auth": {
          "host": "0.0.0.0",
          "port": 9099
        },
        "firestore": {
          "host": "0.0.0.0",
          "port": 8080
        },
        "storage": {
          "host": "0.0.0.0",
          "port": 9199
        }
      },
      "storage": {
        "rules": "storage.rules"
      }
    }
  storage.rules: |
    rules_version = '2';
    service firebase.storage {
      match /b/{bucket}/o {
        match /{allPaths=**} {
          allow read, write: if false;
        }
      }
    }
