---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        # cloud.google.com/gke-nodepool: main
      volumes:
        - name: pg-init
          configMap:
            name: postgres-config
            items:
              - key: init.sql
                path: init.sql
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /data/postgres
          volumeMounts:
            - name: pg-init
              mountPath: /docker-entrypoint-initdb.d
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: api
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: api
#   minReplicas: {{ .Values.minReplicas }}
#   maxReplicas: {{ .Values.maxReplicas }}
#   metrics:
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 70
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 100

