---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        # cloud.google.com/gke-nodepool: main
      volumes:
        - name: database-config
          configMap:
            name: api-config
            items:
              - key: database.config.yaml
                path: local.config.yaml
      containers:
        - name: api
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
          {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | squote }}
          {{- end }}
          volumeMounts:
            - name: database-config
              mountPath: /usr/src/app/src/config/database
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: api
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: api
#   minReplicas: {{ .Values.minReplicas }}
#   maxReplicas: {{ .Values.maxReplicas }}
#   metrics:
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 70
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 100

